name: My First GitHub Action

on:
  pull_request:
    types: [opened]

jobs:
  explorer-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading repo
        uses: actions/checkout@v4

      - name: Exploring runner
        run: |
          echo "Current Directory:"
          pwd

          echo "Files:"
          ls -lah

          echo "Current User:"
          whoami

          echo "Operating System:"
          uname -a

          echo "Current Java Version:"
          java -version
