name: My First GitHub Action

on:
  pull_request:
    types: [opened]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading repo
        uses: actions/checkout@v4

      - name: Print Hello
        run: |
          echo "Hello Akshay"
          pwd
          ls -la
          docker -v