name: My First GitHub Action

on:
  pull_request:
    types: [opened]

jobs:
  explorer-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading repo
        uses: actions/checkout@v4

      - name: Compile Java Class
        run: javac Deployment.java
      
      - name: Verify Class file
        run: find . -name "*.class"
